version: 2

models:
  - name: stg_average_survival_by_sex
    description: "Staging table for average survival by sex with cleaned and typed columns"
    columns:
      - name: year
        description: "Year of observation"
      - name: sex
        description: "Sex of the group (M/F)"
      - name: median_survival
        description: "Median survival time (50th percentile)"

  - name: stg_age_specific_mortality_rate
    description: "Staging table for Aget Specific Mortality Rate data with cleaned columns and normalized sex"
    columns:
      - name: sex
        description: "Sex of the group (M/F)"
      - name: year
        description: "Year of observation"
      - name: age_category
        description: "Age category of the observation"
      - name: deaths
        description: "Number of deaths"
      - name: person_years_observed
        description: "Person-years observed (PYO)"
      - name: births
        description: "Number of births"

  - name: stg_seasonality
    description: "Staging table for age-specific mortality (no sex column)"
    columns:
      - name: year
        description: "Year of observation"
      - name: month
        description: "Month of observation"
      - name: age_category
        description: "Age category (whole numbers only)"
      - name: deaths
        description: "Number of deaths"
      - name: person_years_observed
        description: "Person-years observed (PYO)"
      - name: y_bloc
        description: "Period block identifier"

  - name: stg_survival_km
    description: "Staging table for Kaplan-Meier survival data with normalized sex and converted time"
    columns:
      - name: sex
        description: "Sex of the group (M/F)"
      - name: y_bloc
        description: "Month-year block of observation"
      - name: months_elapsed
        description: "Elapsed time in months since start of y_bloc"
      - name: years_elapsed
        description: "Elapsed time in years since start of y_bloc"
      - name: survival_probability
        description: "Probability of survival at this time point"

  - name: stg_mbita_core
    description: "Staging table for MBITA core individual-level data with normalized sex and cleaned columns"
    columns:
      - name: rec_number
        description: "Unique record identifier for the dataset"
      - name: country_id
        description: "Country code or identifier for the individual's location"
      - name: centre_id
        description: "Centre or facility ID where the record was collected"
      - name: individual_id
        description: "Unique identifier for the individual"
      - name: sex
        description: "Normalized sex of the individual (M/F/Unknown)"
      - name: date_of_birth
        description: "Date of birth of the individual"
      - name: event_count
        description: "Number of events recorded for the individual"
      - name: event_number
        description: "Sequence number of the event for the individual"
      - name: event_code
        description: "Type or code of the event (ENU, OBE, etc.)"
      - name: event_date
        description: "Date when the event occurred"
      - name: observation_date
        description: "Date when the observation was made"




